# Generated by Django 4.1.4 on 2023-02-13 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('HA TINH', 'HA TINH'), ('NGHE AN', 'NGHE AN'), ('NAM DIN', 'NAM DINH'), ('HAI PHONG', 'HA PHONG'), ('HCM', 'HCM'), ('DIEN BIEN', 'DIEN BIEN'), ('CAO BANG', 'CAO BANG'), ('LANG SON', 'LANG SON'), ('HA GIANG', 'HA GIANG'), ('THANH HOA', 'THANH HOA'), ('NINH BINH', 'NINH BINH'), ('QUANG NINH', 'QUANG NINH'), ('QUANG NAM', 'QUANG NAM'), ('HUE', 'HUE'), ('DA NANG', 'DA NANG'), ('THAI BINH', 'THAI BINH'), ('BAC NINH', 'BAC NINH'), ('NHA TRANG', 'NHA TRANG'), ('QUANG BINH', 'QUANG BINH')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
